version: '3'
services:
  db:
    build: .
    ports:
      - 5434:5432
    env_file:
      my_env.env
    command: > 
      postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d